package test;
// Generated Jun 7, 2018 10:09:55 AM by Hibernate Tools 4.3.1

import pojos.*;
// Generated Jun 7, 2018 10:09:55 AM by Hibernate Tools 4.3.1



/**
 * UserCompound generated by hbm2java
 */
public class UserCompoundBackup  implements java.io.Serializable {


     private String compound;
     private String email;
     private String result;

    public UserCompoundBackup() {
    }

	
    public UserCompoundBackup(String compound) {
        this.compound = compound;
    }
    public UserCompoundBackup(String compound, String email, String result) {
       this.compound = compound;
       this.email = email;
       this.result = result;
    }
   
    public String getCompound() {
        return this.compound;
    }
    
    public void setCompound(String compound) {
        this.compound = compound;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    public String toString(){
        return "{"
                +"\"compound\":\""+compound+"\","
                +"\"email\":\""+email+"\","
                +"\"result\":\""+result+"\""
                +"}";
    }


}


