package pojos;
// Generated Jun 7, 2018 10:50:38 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Date time;
     private String function;
     private String email;
     private String compound;
     private String status;
     private String id;
     private Integer processingTime;

    public Log() {
    }

	
    public Log(Date time) {
        this.time = time;
    }
    public Log(Date time, String function, String email, String compound, String status, String id, Integer processingTime) {
       this.time = time;
       this.function = function;
       this.email = email;
       this.compound = compound;
       this.status = status;
       this.id = id;
       this.processingTime = processingTime;
    }
   
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCompound() {
        return this.compound;
    }
    
    public void setCompound(String compound) {
        this.compound = compound;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getProcessingTime() {
        return this.processingTime;
    }
    
    public void setProcessingTime(Integer processingTime) {
        this.processingTime = processingTime;
    }




}


