package pojos;
// Generated Jun 7, 2018 10:50:38 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String name;
     private String institution;
     private String address;
     private String phone;

    public User() {
    }

	
    public User(String email, String name) {
        this.email = email;
        this.name = name;
    }
    public User(String email, String name, String institution, String address, String phone) {
       this.email = email;
       this.name = name;
       this.institution = institution;
       this.address = address;
       this.phone = phone;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


